#!/usr/bin/env python3

from __future__ import annotations

import re
from collections import OrderedDict
from pathlib import Path


INCLUDE_RE = re.compile(r'^\s*#include\s*([<"])([^>"]+)[>"]\s*$')
ARGON_PREFIX = "argon/"


def ordered_unique(items: list[str]) -> list[str]:
    return list(OrderedDict.fromkeys(items))


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    include_dir = repo_root / "include" / "argon"
    output_path = repo_root / "single_header" / "argon.hh"

    headers = sorted(include_dir.glob("*.hh"))
    if not headers:
        raise SystemExit(f"no headers found under {include_dir}")

    header_map = {header.name: header for header in headers}
    system_includes: list[str] = []
    ordered_headers: list[Path] = []
    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(header: Path) -> None:
        name = header.name
        if name in visited:
            return
        if name in visiting:
            raise RuntimeError(f"cyclic include detected at {header}")

        visiting.add(name)
        for line in header.read_text(encoding="utf-8").splitlines():
            match = INCLUDE_RE.match(line)
            if not match:
                continue

            delimiter, include_name = match.groups()
            if include_name.startswith(ARGON_PREFIX):
                dep_name = include_name.removeprefix(ARGON_PREFIX)
                dep = header_map.get(dep_name)
                if dep is None:
                    raise RuntimeError(f"missing internal header referenced by {header}: {include_name}")
                visit(dep)
            elif delimiter == "<":
                system_includes.append(include_name)

        visiting.remove(name)
        visited.add(name)
        ordered_headers.append(header)

    for header in headers:
        visit(header)

    output_lines = [
        "// This file is generated by script/make_single_header.py.",
        "// Do not edit this file directly.",
        "",
        "#pragma once",
        "",
    ]

    for include_name in ordered_unique(system_includes):
        output_lines.append(f"#include <{include_name}>")

    output_lines.append("")

    for index, header in enumerate(ordered_headers):
        output_lines.append(f"// ---- begin: include/argon/{header.name} ----")
        for line in header.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped == "#pragma once":
                continue
            match = INCLUDE_RE.match(line)
            if match:
                continue
            output_lines.append(line)
        output_lines.append(f"// ---- end: include/argon/{header.name} ----")
        if index != len(ordered_headers) - 1:
            output_lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(output_lines) + "\n", encoding="utf-8")

    print(output_path.relative_to(repo_root))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
