#!/bin/sh
# Generate a single-header amalgamation of cli20.
#
# Usage: make_single_header.sh <include_dir> <output_path>
#
# Requires clang in PATH for dependency-order resolution.
# The original source files are used for content so that platform-specific
# conditional includes (#ifdef _WIN32 etc.) are preserved.

set -eu

if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
  echo "usage: $0 <include_dir> <output_path> [compiler]" >&2
  exit 1
fi

INCLUDE_DIR="$1"
OUTPUT="$2"
CXX="${3:-${CXX:-c++}}"
ENTRY="$INCLUDE_DIR/cli/cli.hh"

# Determine the correct include order by asking the C++ compiler to preprocess
# the entry point.  The compiler emits "# N <file> 1" markers when entering a
# file; the first non-marker content line from each cli header tells us the
# topological order (dependencies always appear before the files that use them).
ORDERED=$("$CXX" -E -I "$INCLUDE_DIR" "$ENTRY" | awk "
  /^# [0-9]+ \".*\/cli\/[^\"]+\"/ {
    f = \$3; gsub(/\"/, \"\", f); current = f; next
  }
  /^# / { current = \"\"; next }
  current != \"\" && !seen[current] && /[^ \t]/ {
    seen[current] = 1; print NR, current
  }
" | sort -n | awk "{print \$2}")

mkdir -p "$(dirname "$OUTPUT")"

{
  echo "// This file is generated by script/make_single_header.sh."
  echo "// Do not edit this file directly."
  echo "#pragma once"
  echo ""
  for header in $ORDERED; do
    echo "// ---- $header ----"
    # Strip #pragma once (replaced by the single one above) and internal
    # cli/ includes (their content is inlined in dependency order).
    sed "/^#pragma once/d; /^#include \"cli\//d" "$header"
    echo ""
  done
} > "$OUTPUT"

echo "$OUTPUT"
