#!/usr/bin/env python3

from __future__ import annotations

import re
from collections import OrderedDict
from pathlib import Path


INCLUDE_RE = re.compile(r'^\s*#include\s*([<"])([^>"]+)[>"]\s*$')
IF_RE = re.compile(r'^\s*#\s*(if|ifdef|ifndef)\b')
ENDIF_RE = re.compile(r'^\s*#\s*endif\b')
CLI20_PREFIX = "cli/"


def ordered_unique(items: list[str]) -> list[str]:
    return list(OrderedDict.fromkeys(items))


def main(include_dir: Path, output_path: Path) -> int:

    headers = sorted(include_dir.glob("*.hh"))
    if not headers:
        raise SystemExit(f"no headers found under {include_dir}")

    header_map = {header.name: header for header in headers}
    system_includes: list[str] = []
    ordered_headers: list[Path] = []
    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(header: Path) -> None:
        name = header.name
        if name in visited:
            return
        if name in visiting:
            raise RuntimeError(f"cyclic include detected at {header}")

        visiting.add(name)
        ifdef_depth = 0
        for line in header.read_text(encoding="utf-8").splitlines():
            if IF_RE.match(line):
                ifdef_depth += 1
            elif ENDIF_RE.match(line):
                ifdef_depth -= 1

            match = INCLUDE_RE.match(line)
            if not match:
                continue

            delimiter, include_name = match.groups()
            if include_name.startswith(CLI20_PREFIX):
                dep_name = include_name.removeprefix(CLI20_PREFIX)
                dep = header_map.get(dep_name)
                if dep is None:
                    raise RuntimeError(f"missing internal header referenced by {header}: {include_name}")
                visit(dep)
            elif delimiter == "<" and ifdef_depth == 0:
                # Only hoist unconditional system includes
                system_includes.append(include_name)

        visiting.remove(name)
        visited.add(name)
        ordered_headers.append(header)

    for header in headers:
        visit(header)

    output_lines = [
        "// This file is generated by script/make_single_header.py.",
        "// Do not edit this file directly.",
        "",
        "#pragma once",
        "",
    ]

    for include_name in ordered_unique(system_includes):
        output_lines.append(f"#include <{include_name}>")

    output_lines.append("")

    for index, header in enumerate(ordered_headers):
        output_lines.append(f"// ---- begin: include/cli/{header.name} ----")
        ifdef_depth = 0
        for line in header.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if IF_RE.match(line):
                ifdef_depth += 1
            elif ENDIF_RE.match(line):
                ifdef_depth -= 1

            if stripped == "#pragma once":
                continue
            match = INCLUDE_RE.match(line)
            if match:
                _, include_name = match.groups()
                if include_name.startswith(CLI20_PREFIX):
                    continue  # inlined via ordered_headers
                if ifdef_depth == 0:
                    continue  # unconditional system include: hoisted to top
                # Conditional system include: keep inline to preserve #ifdef context
            output_lines.append(line)
        output_lines.append(f"// ---- end: include/cli/{header.name} ----")
        if index != len(ordered_headers) - 1:
            output_lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(output_lines) + "\n", encoding="utf-8")

    print(output_path)
    return 0


if __name__ == "__main__":
    import sys
    if len(sys.argv) != 3:
        raise SystemExit(f"usage: {sys.argv[0]} <include_dir> <output_path>")
    raise SystemExit(main(Path(sys.argv[1]), Path(sys.argv[2])))
