import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'tutorial',
    'actions',
    'relations',
    {
      type: 'category',
      label: 'Examples',
      items: [{type: 'autogenerated', dirName: 'examples'}],
    },
    'benchmarks',
  ],
};

export default sidebars;
