// This file is generated by script/make_single_header.py.
// Do not edit this file directly.

#pragma once

#include <algorithm>
#include <array>
#include <charconv>
#include <cstdint>
#include <expected>
#include <format>
#include <functional>
#include <span>
#include <string>
#include <string_view>
#include <system_error>
#include <unordered_map>
#include <unordered_set>
#include <vector>

// ---- begin: include/argon/string_literal.hh ----

namespace argon {
template <std::size_t N>
struct StringLiteral {
  std::array<char, N> value{};

  // NOLINTNEXTLINE(cppcoreguidelines-avoid-c-arrays, modernize-avoid-c-arrays)
  consteval StringLiteral(const char (&str)[N]) noexcept { std::copy_n(str, N, value.begin()); }

  [[nodiscard]]
  consteval auto size() const noexcept -> std::size_t {
    return N - 1;
  }

  [[nodiscard]]
  consteval auto data() const noexcept -> const char* {
    return value.data();
  }

  [[nodiscard]]
  consteval auto view() const noexcept -> std::string_view {
    return {value.data(), size()};
  }

  [[nodiscard]]
  consteval auto operator[](std::size_t i) const noexcept -> char {
    return value[i];
  }

  consteval auto operator==(const StringLiteral&) const noexcept -> bool = default;
};

template <std::size_t N>
// NOLINTNEXTLINE(cppcoreguidelines-avoid-c-arrays, modernize-avoid-c-arrays)
StringLiteral(const char (&)[N]) -> StringLiteral<N>;

}  // namespace argon
// ---- end: include/argon/string_literal.hh ----

// ---- begin: include/argon/argument.hh ----

namespace argon {

template <class>
class Parser;

// Whitelist of all value types that Arg<T> supports.
// The primary Arg template is constrained to !parsable_type<T> so it only
// fires a static_assert for truly unsupported types.
template <typename T>
concept parsable_type =
    std::same_as<T, int> || std::same_as<T, int32_t> || std::same_as<T, int64_t> ||
    std::same_as<T, uint32_t> || std::same_as<T, uint64_t> || std::same_as<T, float> ||
    std::same_as<T, double> || std::same_as<T, bool> || std::same_as<T, std::string> ||
    std::same_as<T, std::vector<int>> || std::same_as<T, std::vector<int32_t>> ||
    std::same_as<T, std::vector<int64_t>> || std::same_as<T, std::vector<uint32_t>> ||
    std::same_as<T, std::vector<uint64_t>> || std::same_as<T, std::vector<float>> ||
    std::same_as<T, std::vector<double>> || std::same_as<T, std::vector<bool>> ||
    std::same_as<T, std::vector<std::string>>;

struct ArgumentTag {};

enum class ArgumentType : std::uint8_t {
  flag,
  option,
  positional,
  command,
};

enum class Requirement : std::uint8_t {
  optional,
  required,
};

namespace detail {

template <StringLiteral Name>
[[nodiscard]]
constexpr auto IsValidLongOpt() noexcept -> bool {
  constexpr auto size = Name.size();

  if constexpr (size == 0) {
    return false;
  }
  auto is_alpha = [&](char c) consteval -> bool { return ('a' <= c && c <= 'z'); };
  auto is_digit = [](char c) consteval -> bool { return '0' <= c && c <= '9'; };
  auto is_alnum = [&](char c) consteval -> bool { return is_alpha(c) || is_digit(c); };

  if (!is_alpha(Name[0])) {
    return false;
  }
  bool previous_is_hyphen = false;
  for (std::size_t i = 1; i < size; ++i) {
    const char c = Name[i];
    if (c == '-') {
      if (previous_is_hyphen) {
        return false;
      }
      previous_is_hyphen = true;
      continue;
    }
    if (!is_alnum(c)) {
      return false;
    }
    previous_is_hyphen = false;
  }

  return !previous_is_hyphen;
}

constexpr auto IsValidShortOpt(char Name) noexcept -> bool {
  return ('a' <= Name && Name <= 'z') || ('A' <= Name && Name <= 'Z') || Name == '\0';
}

template <StringLiteral Name>
[[nodiscard]]
consteval auto IsCommandName() noexcept {
  return IsValidLongOpt<Name>();
}

struct Nargs {
  std::size_t min;
  std::optional<std::size_t> max;
};

}  // namespace detail

namespace nargs {

inline constexpr detail::Nargs none{.min = 0, .max = 0};
inline constexpr detail::Nargs one{.min = 1, .max = 1};
inline constexpr detail::Nargs optional{.min = 0, .max = 1};
inline constexpr detail::Nargs zero_or_more{.min = 0, .max = std::nullopt};
inline constexpr detail::Nargs one_or_more{.min = 1, .max = std::nullopt};

template <std::size_t N>
inline constexpr detail::Nargs exactly{.min = N, .max = N};

template <std::size_t Min, std::size_t Max>
inline constexpr detail::Nargs between{.min = Min, .max = Max};

}  // namespace nargs

inline constexpr Requirement optional = Requirement::optional;
inline constexpr Requirement required = Requirement::required;

template <typename ValueT, StringLiteral LongOpt, char ShortOpt>
  requires(detail::IsValidShortOpt(ShortOpt) && detail::IsValidLongOpt<LongOpt>())
struct ArgBase : ArgumentTag {
  static constexpr auto type = ArgumentType::option;
  using value_type = ValueT;

  static constexpr auto long_opt = LongOpt;
  static constexpr char short_opt = ShortOpt;

  constexpr explicit ArgBase(Requirement requirement = optional) : requirement_(requirement) {}

  [[nodiscard]] static constexpr auto longOpt() noexcept -> std::string_view {
    return LongOpt.view();
  }
  [[nodiscard]] static constexpr auto shortOpt() noexcept -> char { return ShortOpt; }
  [[nodiscard]] constexpr auto requirement() const noexcept -> Requirement { return requirement_; }
  [[nodiscard]] constexpr auto isRequired() const noexcept -> bool {
    return requirement_ == required;
  }
  [[nodiscard]] constexpr auto value() const noexcept -> const ValueT& { return value_; }
  [[nodiscard]] constexpr auto provided() const noexcept -> bool { return occurrence_count_ != 0; }
  [[nodiscard]] constexpr auto occurrenceCount() const noexcept -> std::size_t {
    return occurrence_count_;
  }

 protected:
  constexpr auto valueRef() noexcept -> ValueT& { return value_; }
  constexpr auto markProvided() noexcept -> void { ++occurrence_count_; }

 private:
  Requirement requirement_ = optional;
  std::size_t occurrence_count_ = 0;
  ValueT value_ = {};
};

template <typename ValueT>
struct PositionalArgument : ArgumentTag {
  static constexpr auto type = ArgumentType::positional;
  using value_type = ValueT;

  constexpr PositionalArgument(Requirement requirement = optional) : requirement_(requirement) {}

  [[nodiscard]] constexpr auto value() const noexcept -> const ValueT& { return value_; }
  [[nodiscard]] constexpr auto provided() const noexcept -> bool { return provided_; }
  [[nodiscard]] constexpr auto isRequired() const noexcept -> bool {
    return requirement_ == Requirement::required;
  }

  template <class>
  friend class Parser;

 protected:
  [[nodiscard]] constexpr auto valueRef() noexcept -> ValueT& { return value_; }
  constexpr auto markProvided() noexcept -> void { provided_ = true; }

 private:
  Requirement requirement_ = optional;
  ValueT value_{};
  bool provided_ = false;
};

template <typename ValueT, StringLiteral LongOpt, char ShortOpt>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
struct Arg : public ArgBase<ValueT, LongOpt, ShortOpt> {
  static_assert([]<typename T = ValueT>() consteval -> auto { return parsable_type<T>; }(),
                "Arg<ValueT>: unsupported value type. "
                "Supported: int/int32_t/int64_t/uint32_t/uint64_t/float/double "
                "(arithmetic_argument.hh); std::string (string_argument.hh); "
                "bool (bool_argument.hh); std::vector<T> of any of the above.");
};

template <class T, StringLiteral CommandName>
  requires(detail::IsCommandName<CommandName>())
struct Command : ArgumentTag, public T {
  using args_type = T;
  static constexpr auto type = ArgumentType::command;

  [[nodiscard]] constexpr auto provided() const noexcept -> bool { return provided_; }

 protected:
  [[nodiscard]] static constexpr auto commandName() -> std::string_view {
    return CommandName.view();
  }
  constexpr auto markProvided() noexcept -> void { provided_ = true; }

  template <class>
  friend class Parser;

 private:
  bool provided_ = false;
};

}  // namespace argon
// ---- end: include/argon/argument.hh ----

// ---- begin: include/argon/error.hh ----

namespace argon {

enum class ErrorCode {
  unknown_option,
  unknown_command,
  unexpected_argument,
  missing_value,
  invalid_value,
  duplicate_argument,

  conversion_error,
  out_of_range,
  missing_required,
  mutually_exclusive,
  dependency_missing,
  invalid_choice,
  validation_failed,
  unknown_error,
};

enum class ErrorKind {
  parse,
  conversion,
  validation,
};

[[nodiscard]] constexpr auto toString(ErrorCode code) noexcept -> std::string_view {
  switch (code) {
    case ErrorCode::unknown_option:
      return "unknown option";
    case ErrorCode::unknown_command:
      return "unknown command";
    case ErrorCode::unexpected_argument:
      return "unexpected argument";
    case ErrorCode::missing_value:
      return "missing value";
    case ErrorCode::invalid_value:
      return "invalid value";
    case ErrorCode::duplicate_argument:
      return "duplicate argument";
    case ErrorCode::conversion_error:
      return "conversion error";
    case ErrorCode::out_of_range:
      return "out of range";
    case ErrorCode::missing_required:
      return "missing required argument";
    case ErrorCode::mutually_exclusive:
      return "mutually exclusive argument";
    case ErrorCode::dependency_missing:
      return "dependency missing";
    case ErrorCode::invalid_choice:
      return "invalid choice";
    case ErrorCode::validation_failed:
      return "validation failed";
    case ErrorCode::unknown_error:
      return "unknown error";
  }

  return "unknown error";
}

struct ParseError {
  ErrorCode code = ErrorCode::unknown_error;
  ErrorKind kind = ErrorKind::parse;

  int position = -1;

  std::string subject{};
  std::string detail{};

  [[nodiscard]] constexpr auto hasPosition() const noexcept -> bool { return position >= 0; }

  [[nodiscard]] auto message() const -> std::string {
    std::string out{toString(code)};
    if (!subject.empty()) {
      out += ": ";
      out += subject;
    }

    if (!detail.empty()) {
      out += " (";
      out += detail;
      out += ")";
    }

    if (hasPosition()) {
      out += " at argv[";
      out += std::to_string(position);
      out += "]";
    }

    return out;
  }

  [[nodiscard]] auto hasError() const noexcept -> bool { return code != ErrorCode::unknown_error; }
};

}  // namespace argon
// ---- end: include/argon/error.hh ----

// ---- begin: include/argon/arithmetic_argument.hh ----

namespace argon {

namespace detail {

// Parse a single arithmetic value from a string_view via std::from_chars.
// Returns result_out_of_range on overflow, invalid_argument on bad input / partial parse.
template <typename T>
  requires((std::integral<T> && !std::same_as<std::remove_cv_t<T>, bool>) || std::floating_point<T>)
auto parseArithmetic(std::string_view sv, T& out) -> std::expected<void, ParseError> {
  const char* first = sv.data();
  // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-pointer-arithmetic)
  const char* last = first + sv.size();
  std::from_chars_result res{};
  if constexpr (std::floating_point<T>) {
    res = std::from_chars(first, last, out, std::chars_format::general);
  } else {
    res = std::from_chars(first, last, out);
  }
  if (res.ec != std::errc() || res.ptr != last) {
    return std::unexpected(ParseError{.code = ErrorCode::conversion_error,
                                      .kind = ErrorKind::conversion,
                                      .subject = std::string(sv)});
  }
  return {};
}

// Shared implementation base for single-value arithmetic Arg specializations.
template <typename T, StringLiteral LongOpt, char ShortOpt>
struct ArithmeticArgImpl : public ArgBase<T, LongOpt, ShortOpt> {
  using ArgBase<T, LongOpt, ShortOpt>::ArgBase;
  template <class>
  friend class Parser;

 protected:
  auto parse(std::span<const std::string_view> sv) -> std::expected<void, ParseError> {
    return parseArithmetic(sv[0], this->valueRef());
  }

  [[nodiscard]] auto nargs() const noexcept -> Nargs { return nargs_; }

 private:
  Nargs nargs_ = nargs::one;
};

// Shared implementation base for single-value arithmetic PositionalArgument specializations.
template <typename T>
struct ArithmeticPositionalImpl : ArgumentTag {
  static constexpr auto type = ArgumentType::positional;
  using value_type = T;

  constexpr ArithmeticPositionalImpl(Requirement requirement = optional)
      : requirement_(requirement) {}

  [[nodiscard]] constexpr auto value() const noexcept -> const T& { return value_; }
  [[nodiscard]] constexpr auto provided() const noexcept -> bool { return provided_; }
  [[nodiscard]] constexpr auto isRequired() const noexcept -> bool {
    return requirement_ == Requirement::required;
  }

  template <class>
  friend class Parser;

 protected:
  [[nodiscard]] constexpr auto valueRef() noexcept -> T& { return value_; }
  constexpr auto markProvided() noexcept -> void { provided_ = true; }

  auto parse(std::string_view sv) -> std::expected<void, ParseError> {
    return parseArithmetic(sv, value_);
  }

 private:
  Requirement requirement_ = optional;
  T value_{};
  bool provided_ = false;
};

}  // namespace detail

// ---- Arg<T, ...> explicit specializations for each arithmetic type ----
//
// Specializations are defined for the underlying fundamental C++ types rather than
// fixed-width typedef aliases (e.g. int rather than int32_t), since typedefs may alias
// the same underlying type on a given platform (int32_t == int on most 64-bit targets)
// and two specializations for the same type would be a redefinition error.
// The public aliases (Int32Arg, Int64Arg, etc.) resolve correctly because int32_t,
// int64_t, etc. are guaranteed to alias one of the fundamental types below.

// NOLINTNEXTLINE(cppcoreguidelines-macro-usage)
#define ARGON_ARITHMETIC_ARG_SPEC(T)                                                          \
  template <StringLiteral LongOpt, char ShortOpt>                                             \
    requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))          \
  struct Arg<T, LongOpt, ShortOpt> : public detail::ArithmeticArgImpl<T, LongOpt, ShortOpt> { \
    using detail::ArithmeticArgImpl<T, LongOpt, ShortOpt>::ArithmeticArgImpl;                 \
    template <class> /* NOLINT(bugprone-forward-declaration-namespace) */                     \
    friend class Parser;                                                                      \
  };

ARGON_ARITHMETIC_ARG_SPEC(int)
ARGON_ARITHMETIC_ARG_SPEC(long)       // NOLINT(google-runtime-int)
ARGON_ARITHMETIC_ARG_SPEC(long long)  // NOLINT(google-runtime-int)
ARGON_ARITHMETIC_ARG_SPEC(unsigned int)
ARGON_ARITHMETIC_ARG_SPEC(unsigned long)       // NOLINT(google-runtime-int)
ARGON_ARITHMETIC_ARG_SPEC(unsigned long long)  // NOLINT(google-runtime-int)
ARGON_ARITHMETIC_ARG_SPEC(float)
ARGON_ARITHMETIC_ARG_SPEC(double)

#undef ARGON_ARITHMETIC_ARG_SPEC

// ---- PositionalArgument<T> explicit specializations for each arithmetic type ----

// NOLINTNEXTLINE(cppcoreguidelines-macro-usage)
#define ARGON_ARITHMETIC_POSITIONAL_SPEC(T)                                   \
  template <>                                                                 \
  struct PositionalArgument<T> : public detail::ArithmeticPositionalImpl<T> { \
    using detail::ArithmeticPositionalImpl<T>::ArithmeticPositionalImpl;      \
    template <class>                                                          \
    friend class Parser;                                                      \
  };

ARGON_ARITHMETIC_POSITIONAL_SPEC(int)
ARGON_ARITHMETIC_POSITIONAL_SPEC(long)       // NOLINT(google-runtime-int)
ARGON_ARITHMETIC_POSITIONAL_SPEC(long long)  // NOLINT(google-runtime-int)
ARGON_ARITHMETIC_POSITIONAL_SPEC(unsigned int)
ARGON_ARITHMETIC_POSITIONAL_SPEC(unsigned long)       // NOLINT(google-runtime-int)
ARGON_ARITHMETIC_POSITIONAL_SPEC(unsigned long long)  // NOLINT(google-runtime-int)
ARGON_ARITHMETIC_POSITIONAL_SPEC(float)
ARGON_ARITHMETIC_POSITIONAL_SPEC(double)

#undef ARGON_ARITHMETIC_POSITIONAL_SPEC

// ---- Arg<std::vector<T>, ...> for arithmetic element types (one-or-more values) ----

template <typename T, StringLiteral LongOpt, char ShortOpt>
  requires((std::integral<T> && !std::same_as<std::remove_cv_t<T>, bool>) ||
           std::floating_point<T>) &&
          (detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
struct Arg<std::vector<T>, LongOpt, ShortOpt> : public ArgBase<std::vector<T>, LongOpt, ShortOpt> {
  using Base = ArgBase<std::vector<T>, LongOpt, ShortOpt>;
  template <class>
  friend class Parser;

  constexpr explicit Arg(Requirement requirement, detail::Nargs nargs = nargs::one_or_more)
      : Base(requirement), nargs_(nargs) {}

  constexpr explicit Arg(detail::Nargs nargs = nargs::one_or_more)
      : Base(optional), nargs_(nargs) {}

 protected:
  auto parse(std::span<const std::string_view> sv) -> std::expected<void, ParseError> {
    auto& out = this->valueRef();
    out.clear();
    for (const auto& s : sv) {
      T val{};
      if (auto r = detail::parseArithmetic(s, val); !r) return r;
      out.push_back(val);
    }
    return {};
  }

  auto validate() -> std::expected<void, ParseError> { return {}; }
  [[nodiscard]] auto nargs() const noexcept -> detail::Nargs { return nargs_; }

 private:
  detail::Nargs nargs_ = nargs::one_or_more;
};

// ---- Single-value aliases ----

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using IntArg = Arg<int, LongOpt, ShortOpt>;

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using Int32Arg = Arg<int32_t, LongOpt, ShortOpt>;

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using Int64Arg = Arg<int64_t, LongOpt, ShortOpt>;

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using Uint32Arg = Arg<uint32_t, LongOpt, ShortOpt>;

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using Uint64Arg = Arg<uint64_t, LongOpt, ShortOpt>;

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using FloatArg = Arg<float, LongOpt, ShortOpt>;

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using DoubleArg = Arg<double, LongOpt, ShortOpt>;

// ---- List aliases ----

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using IntListArg = Arg<std::vector<int>, LongOpt, ShortOpt>;

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using Int32ListArg = Arg<std::vector<int32_t>, LongOpt, ShortOpt>;

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using Int64ListArg = Arg<std::vector<int64_t>, LongOpt, ShortOpt>;

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using Uint32ListArg = Arg<std::vector<uint32_t>, LongOpt, ShortOpt>;

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using Uint64ListArg = Arg<std::vector<uint64_t>, LongOpt, ShortOpt>;

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using FloatListArg = Arg<std::vector<float>, LongOpt, ShortOpt>;

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using DoubleListArg = Arg<std::vector<double>, LongOpt, ShortOpt>;

// ---- Positional aliases ----

using IntPositional = PositionalArgument<int>;
using Int32Positional = PositionalArgument<int32_t>;
using Int64Positional = PositionalArgument<int64_t>;
using Uint32Positional = PositionalArgument<uint32_t>;
using Uint64Positional = PositionalArgument<uint64_t>;
using FloatPositional = PositionalArgument<float>;
using DoublePositional = PositionalArgument<double>;

using IntPositionalArg = IntPositional;
using Int32PositionalArg = Int32Positional;
using Int64PositionalArg = Int64Positional;
using Uint32PositionalArg = Uint32Positional;
using Uint64PositionalArg = Uint64Positional;
using FloatPositionalArg = FloatPositional;
using DoublePositionalArg = DoublePositional;

using IntPosArg = IntPositional;
using Int32PosArg = Int32Positional;
using Int64PosArg = Int64Positional;
using Uint32PosArg = Uint32Positional;
using Uint64PosArg = Uint64Positional;
using FloatPosArg = FloatPositional;
using DoublePosArg = DoublePositional;

}  // namespace argon
// ---- end: include/argon/arithmetic_argument.hh ----

// ---- begin: include/argon/bool_argument.hh ----

namespace argon {

namespace detail {

inline auto parseBool(std::string_view sv, bool& out) -> std::expected<void, ParseError> {
  if (sv == "true") {
    out = true;
    return {};
  }
  if (sv == "false") {
    out = false;
    return {};
  }
  return std::unexpected(ParseError{.code = ErrorCode::conversion_error,
                                    .kind = ErrorKind::conversion,
                                    .subject = std::string(sv)});
}

}  // namespace detail

// ---- Arg<bool, ...> (single value, accepts "true" or "false") ----

template <StringLiteral LongOpt, char ShortOpt>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
struct Arg<bool, LongOpt, ShortOpt> : public ArgBase<bool, LongOpt, ShortOpt> {
  using ArgBase<bool, LongOpt, ShortOpt>::ArgBase;
  template <class>
  friend class Parser;

 protected:
  auto parse(std::span<const std::string_view> sv) -> std::expected<void, ParseError> {
    return detail::parseBool(sv[0], this->valueRef());
  }

  auto validate() -> std::expected<void, ParseError> { return {}; }
  [[nodiscard]] auto nargs() const noexcept -> detail::Nargs { return nargs_; }

 private:
  detail::Nargs nargs_ = nargs::one;
};

// ---- PositionalArgument<bool> ----

template <>
struct PositionalArgument<bool> : ArgumentTag {
  static constexpr auto type = ArgumentType::positional;
  using value_type = bool;

  constexpr PositionalArgument(Requirement requirement = optional) : requirement_(requirement) {}

  [[nodiscard]] constexpr auto value() const noexcept -> bool { return value_; }
  [[nodiscard]] constexpr auto provided() const noexcept -> bool { return provided_; }
  [[nodiscard]] constexpr auto isRequired() const noexcept -> bool {
    return requirement_ == Requirement::required;
  }

  template <class>
  friend class Parser;

 protected:
  auto parse(std::string_view sv) -> std::expected<void, ParseError> {
    return detail::parseBool(sv, value_);
  }

  constexpr auto markProvided() noexcept -> void { provided_ = true; }

 private:
  Requirement requirement_ = optional;
  bool value_ = false;
  bool provided_ = false;
};

// ---- Arg<std::vector<bool>, ...> (one-or-more values) ----

template <StringLiteral LongOpt, char ShortOpt>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
struct Arg<std::vector<bool>, LongOpt, ShortOpt>
    : public ArgBase<std::vector<bool>, LongOpt, ShortOpt> {
  using Base = ArgBase<std::vector<bool>, LongOpt, ShortOpt>;
  template <class>
  friend class Parser;

  constexpr explicit Arg(Requirement requirement, detail::Nargs nargs = nargs::one_or_more)
      : Base(requirement), nargs_(nargs) {}

  constexpr explicit Arg(detail::Nargs nargs = nargs::one_or_more)
      : Base(optional), nargs_(nargs) {}

 protected:
  auto parse(std::span<const std::string_view> sv) -> std::expected<void, ParseError> {
    auto& out = this->valueRef();
    out.clear();
    for (const auto& s : sv) {
      bool val = false;
      if (auto r = detail::parseBool(s, val); !r) return r;
      out.push_back(val);
    }
    return {};
  }

  auto validate() -> std::expected<void, ParseError> { return {}; }
  [[nodiscard]] auto nargs() const noexcept -> detail::Nargs { return nargs_; }

 private:
  detail::Nargs nargs_ = nargs::one_or_more;
};

// ---- Aliases ----

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using BoolArg = Arg<bool, LongOpt, ShortOpt>;

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using BoolListArg = Arg<std::vector<bool>, LongOpt, ShortOpt>;

using BoolPositional = PositionalArgument<bool>;
using BoolPositionalArg = BoolPositional;
using BoolPosArg = BoolPositional;

}  // namespace argon
// ---- end: include/argon/bool_argument.hh ----

// ---- begin: include/argon/constraints.hh ----

namespace argon {};

// ---- end: include/argon/constraints.hh ----

// ---- begin: include/argon/flag_argument.hh ----

namespace argon {

template <StringLiteral LongOpt, char ShortOpt>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
struct Flag : ArgumentTag {
  static constexpr auto type = ArgumentType::flag;

  [[nodiscard]] constexpr auto provided() const noexcept -> bool { return provided_; }

 protected:
  [[nodiscard]] static constexpr auto longOpt() -> std::string_view { return LongOpt.view(); }
  [[nodiscard]] static constexpr auto shortOpt() -> char { return ShortOpt; }

  template <class>
  friend class Parser;

  [[nodiscard]] auto nargs() const noexcept -> detail::Nargs { return nargs_; }
  constexpr auto markProvided() noexcept -> void { provided_ = true; }

 private:
  detail::Nargs nargs_ = nargs::none;
  bool provided_ = false;
};

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using FlagArg = Flag<LongOpt, ShortOpt>;

}  // namespace argon
// ---- end: include/argon/flag_argument.hh ----

// ---- begin: include/argon/parser.hh ----

namespace argon {

namespace detail {

template <class Argument>
constexpr auto castBaseIfCommand(Argument& arg) -> auto& {
  if constexpr (requires {
                  Argument::type;
                  Argument::type == ArgumentType::command;
                }) {
    return static_cast<Argument::args_type&>(arg);
  } else {
    return arg;
  }
}

template <class Arguments>
struct isValidArgumentsType {
  static constexpr bool value = [] -> bool {
    if constexpr (!std::derived_from<std::remove_cvref_t<Arguments>, ArgumentTag>) {
      auto&& [... options] = Arguments{};
      return (... && (std::derived_from<std::remove_cvref_t<decltype(options)>, ArgumentTag>));
    }
    return false;
  }();
};

struct TokenizeResult {
  std::unordered_map<std::string, std::vector<std::string_view>> named;
  std::vector<std::string_view> positional;
  // Set when a command name is encountered; points from that token to end of args.
  std::optional<std::span<const std::string_view>> command_tail;
};

// spec_map      : option/flag keys → nargs  (does NOT contain command names)
// command_names : set of bare command name strings (no "--" prefix)
inline auto tokenize(std::span<const std::string_view> args,
                     const std::unordered_map<std::string, Nargs>& spec_map,
                     const std::unordered_set<std::string>& command_names = {})
    -> std::expected<TokenizeResult, ParseError> {
  TokenizeResult result;

  for (std::size_t i = 0; i < args.size(); ++i) {
    const auto arg = args[i];

    // "--" end-of-options separator: everything after is positional
    if (arg == "--") {
      for (std::size_t j = i + 1; j < args.size(); ++j) {
        result.positional.push_back(args[j]);
      }
      break;
    }

    // Command name: stop parsing at this level; hand off remainder to sub-parser
    if (command_names.contains(std::string(arg))) {
      result.command_tail = args.subspan(i);
      break;
    }

    // --foo=bar syntax: only recognized when nargs is exact<1>
    if (arg.starts_with("--")) {
      if (const auto eq = arg.find('='); eq != std::string_view::npos) {
        const auto key = std::string(arg.substr(0, eq));
        const auto val = arg.substr(eq + 1);
        const auto it = spec_map.find(key);
        if (it != spec_map.end() && it->second.min == 1 &&
            it->second.max == std::optional<std::size_t>{1}) {
          if (result.named.contains(key)) {
            return std::unexpected(ParseError{.code = ErrorCode::duplicate_argument,
                                              .kind = ErrorKind::parse,
                                              .position = static_cast<int>(i),
                                              .subject = key,
                                              .detail = "option specified multiple times"});
          }
          result.named[key].push_back(val);
        } else {
          result.positional.push_back(arg);
        }
        continue;
      }
    }

    // Look up the token in spec_map
    const auto it = spec_map.find(std::string(arg));
    if (it == spec_map.end()) {
      result.positional.push_back(arg);
      continue;
    }

    const auto key = std::string(arg);
    if (result.named.contains(key)) {
      return std::unexpected(ParseError{.code = ErrorCode::duplicate_argument,
                                        .kind = ErrorKind::parse,
                                        .position = static_cast<int>(i),
                                        .subject = key,
                                        .detail = "option specified multiple times"});
    }

    // Collect values up to max, stopping at the next option/command/separator
    const auto& nargs_spec = it->second;
    auto& values = result.named[key];
    for (std::size_t count = 0;
         i + 1 < args.size() && (!nargs_spec.max.has_value() || count < *nargs_spec.max) &&
         args[i + 1] != "--" && !spec_map.contains(std::string(args[i + 1])) &&
         !command_names.contains(std::string(args[i + 1]));
         ++count) {
      values.push_back(args[++i]);
    }

    if (values.size() < nargs_spec.min) {
      return std::unexpected(ParseError{
          .code = ErrorCode::missing_value,
          .kind = ErrorKind::parse,
          .position = static_cast<int>(i),
          .subject = key,
          .detail = std::format("option requires at least {} value(s), but only {} provided",
                                nargs_spec.min, values.size())});
    }
  }

  return result;
}

}  // namespace detail

template <class Arguments>
class Parser {
  static_assert(detail::isValidArgumentsType<Arguments>::value,
                "Arguments must be a struct or nested struct containing only Argument types");

 private:
  template <class T = Arguments>
  static consteval auto hasDuplicateOptions() -> bool {
    std::vector<std::string> options;
    auto t = T{};
    auto [... args] = detail::castBaseIfCommand(t);

    if ((... || [&args] -> bool {
          if constexpr (args.type == ArgumentType::command) {
            return hasDuplicateOptions<std::remove_cvref_t<decltype(args)>>();
          }
          return false;
        }())) {
      return true;
    }

    (..., [&] -> auto {
      if constexpr (args.type == ArgumentType::option || args.type == ArgumentType::flag) {
        options.emplace_back(std::string("--") + args.longOpt());
        if (args.shortOpt() != '\0') {
          options.emplace_back(std::string("-") + args.shortOpt());
        }
      }
      if constexpr (args.type == ArgumentType::command) {
        options.emplace_back(std::string(args.commandName()));
      }
    }());

    std::ranges::sort(options);
    return std::ranges::adjacent_find(options) != options.end();
  }

  static_assert(!hasDuplicateOptions(),
                "Arguments must not contain duplicate long or short options");

 public:
  [[nodiscard]]
  // NOLINTNEXTLINE(cppcoreguidelines-avoid-c-arrays, modernize-avoid-c-arrays)
  auto parse(int argc, char* argv[]) -> std::expected<Arguments, ParseError> {
    std::vector<std::string_view> args;
    args.reserve(static_cast<std::size_t>(argc));
    for (char* arg : std::span<char*>{argv, static_cast<std::size_t>(argc)}) {
      args.emplace_back(arg);
    }
    return parse(args);
  }

  auto parse(std::span<const std::string_view> args) -> std::expected<Arguments, ParseError> {
    Arguments result;
    if (auto r = parse(args, result); !r) {
      return std::unexpected(r.error());
    }
    return result;
  }

  auto parse(std::span<const std::string_view> args, Arguments& out)
      -> std::expected<void, ParseError> {
    program_name_ = args.empty() ? "program" : std::string(args[0]);

    const auto rest = args.size() > 1 ? args.subspan(1) : std::span<const std::string_view>{};

    auto specMap = makeOptionSpecMap(out);
    auto cmdNames = makeCommandNamesSet(out);

    auto tokenized = detail::tokenize(rest, specMap, cmdNames);
    if (!tokenized) {
      return std::unexpected(tokenized.error());
    }

    auto parseMap = makeParseMap(out);

    for (const auto& [key, values] : tokenized->named) {
      const auto it = parseMap.find(key);
      if (it != parseMap.end()) {
        auto r = it->second(values);
        if (!r) {
          return std::unexpected(r.error());
        }
      }
    }

    // Assign positionals and check required options
    auto& [... opts] = out;
    std::size_t pos_idx = 0;
    ParseError pos_error;
    std::string missing;
    (..., [&] -> auto {
      if constexpr (opts.type == ArgumentType::positional) {
        if (pos_idx < tokenized->positional.size()) {
          const auto sv = tokenized->positional[pos_idx++];
          if constexpr (requires { opts.parse(sv); }) {
            if (!pos_error.hasError()) {
              auto r = opts.parse(sv);
              if (!r) {
                pos_error = r.error();
              } else {
                opts.markProvided();
              }
            }
          }
        } else {
          if constexpr (requires { opts.isRequired(); }) {
            if (opts.isRequired() && !pos_error.hasError()) {
              pos_error = ParseError{
                  .code = ErrorCode::missing_value,
                  .kind = ErrorKind::parse,
                  .position = static_cast<int>(args.size()),
                  .subject = std::format("positional argument at position {}", pos_idx + 1)};
            }
          }
          ++pos_idx;
        }
      }
      if constexpr (opts.type == ArgumentType::option) {
        if (opts.isRequired() && !opts.provided() && missing.empty()) {
          missing = std::string("--") + std::string(opts.longOpt());
        }
      }
    }());
    if (pos_error.hasError()) {
      return std::unexpected(pos_error);
    }
    if (!missing.empty()) {
      return std::unexpected(ParseError{.code = ErrorCode::missing_value,
                                        .kind = ErrorKind::parse,
                                        .position = static_cast<int>(args.size()),
                                        .subject = missing,
                                        .detail = "required option was not provided"});
    }

    // Recursively parse sub-command if one was encountered
    if (tokenized->command_tail) {
      ParseError cmd_error;
      (..., [&] -> auto {
        if constexpr (opts.type == ArgumentType::command) {
          const auto& tail = *tokenized->command_tail;
          if (!tail.empty() && tail[0] == opts.commandName() && !cmd_error.hasError()) {
            using SubArgs = std::remove_cvref_t<decltype(detail::castBaseIfCommand(opts))>;
            Parser<SubArgs> sub_parser;
            if (auto r = sub_parser.parse(tail, detail::castBaseIfCommand(opts)); !r) {
              cmd_error = r.error();
            } else {
              opts.markProvided();
            }
          }
        }
      }());
      if (cmd_error.hasError()) {
        cmd_error.position += static_cast<int>(args.size() - tokenized->command_tail->size());
        return std::unexpected(cmd_error);
      }
    }

    return {};
  }

 private:
  // Build a spec map for options and flags only (commands are handled separately).
  auto makeOptionSpecMap(const Arguments& args) const {
    auto [... options] = args;

    std::unordered_map<std::string, detail::Nargs> specMap;

    (..., [&] -> auto {
      if constexpr (options.type == ArgumentType::option || options.type == ArgumentType::flag) {
        specMap.emplace(std::string("--") + options.longOpt(), options.nargs());
        if (options.shortOpt() != '\0') {
          specMap.emplace(std::string("-") + std::string(1, options.shortOpt()), options.nargs());
        }
      }
    }());
    return specMap;
  }

  // Collect bare command name strings (no "--" prefix).
  auto makeCommandNamesSet(const Arguments& args) const {
    auto [... options] = args;

    std::unordered_set<std::string> cmdNames;

    (..., [&] -> auto {
      if constexpr (options.type == ArgumentType::command) {
        cmdNames.emplace(std::string(options.commandName()));
      }
    }());
    return cmdNames;
  }

  // Build a map from option key (e.g. "--foo", "-f") to a callable that parses
  // the tokenized values into the corresponding field of `args` and marks it as provided.
  // `args` must remain alive for as long as the returned map is used.
  auto makeParseMap(Arguments& args) {
    auto& [... options] = args;

    std::unordered_map<std::string, std::function<std::expected<void, ParseError>(
                                        std::span<const std::string_view>)>>
        parseMap;

    (..., [&] -> auto {
      if constexpr (options.type == ArgumentType::option) {
        auto make_fn =
            [&options](
                std::span<const std::string_view> values) -> std::expected<void, ParseError> {
          auto r = options.parse(values);
          if (!r) {
            return std::unexpected(r.error());
          }
          options.markProvided();
          return {};
        };
        parseMap.emplace(std::string("--") + options.longOpt(), make_fn);
        if (options.shortOpt() != '\0') {
          parseMap.emplace(std::string("-") + std::string(1, options.shortOpt()), make_fn);
        }
      }
      if constexpr (options.type == ArgumentType::flag) {
        auto make_fn =
            [&options](std::span<const std::string_view>) -> std::expected<void, ParseError> {
          options.markProvided();
          return {};
        };
        parseMap.emplace(std::string("--") + options.longOpt(), make_fn);
        if (options.shortOpt() != '\0') {
          parseMap.emplace(std::string("-") + std::string(1, options.shortOpt()), make_fn);
        }
      }
    }());
    return parseMap;
  }

  std::string program_name_ = "program";
};

// ---- Free-function syntax sugar ----

template <class Arguments>
[[nodiscard]]
// NOLINTNEXTLINE(cppcoreguidelines-avoid-c-arrays, modernize-avoid-c-arrays)
auto parse(int argc, char* argv[]) -> std::expected<Arguments, ParseError> {
  return Parser<Arguments>{}.parse(argc, argv);
}

template <class Arguments>
[[nodiscard]]
auto parse(std::span<const std::string_view> args) -> std::expected<Arguments, ParseError> {
  return Parser<Arguments>{}.parse(args);
}

}  // namespace argon
// ---- end: include/argon/parser.hh ----

// ---- begin: include/argon/string_argument.hh ----

namespace argon {

// ---- Arg<std::string, ...> (single value) ----

template <StringLiteral LongOpt, char ShortOpt>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
struct Arg<std::string, LongOpt, ShortOpt> : public ArgBase<std::string, LongOpt, ShortOpt> {
  using ArgBase<std::string, LongOpt, ShortOpt>::ArgBase;
  template <class>
  friend class Parser;

 protected:
  auto parse(std::span<const std::string_view> sv) -> std::expected<void, ParseError> {
    this->valueRef() = std::string(sv[0]);
    return {};
  }

  auto validate() -> std::expected<void, ParseError> { return {}; }
  [[nodiscard]] auto nargs() const noexcept -> detail::Nargs { return nargs_; }

 private:
  detail::Nargs nargs_ = nargs::one;
};

// ---- Arg<std::vector<std::string>, ...> (one-or-more values) ----

template <StringLiteral LongOpt, char ShortOpt>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
struct Arg<std::vector<std::string>, LongOpt, ShortOpt>
    : public ArgBase<std::vector<std::string>, LongOpt, ShortOpt> {
  using Base = ArgBase<std::vector<std::string>, LongOpt, ShortOpt>;
  template <class>
  friend class Parser;

  constexpr explicit Arg(Requirement requirement, detail::Nargs nargs = nargs::one_or_more)
      : Base(requirement), nargs_(nargs) {}

  constexpr explicit Arg(detail::Nargs nargs = nargs::one_or_more)
      : Base(optional), nargs_(nargs) {}

 protected:
  auto parse(std::span<const std::string_view> sv) -> std::expected<void, ParseError> {
    auto& out = this->valueRef();
    out.clear();
    for (const auto& s : sv) {
      out.emplace_back(s);
    }
    return {};
  }

  auto validate() -> std::expected<void, ParseError> { return {}; }
  [[nodiscard]] auto nargs() const noexcept -> detail::Nargs { return nargs_; }

 private:
  detail::Nargs nargs_ = nargs::one_or_more;
};

// ---- PositionalArgument<std::string> ----

template <>
struct PositionalArgument<std::string> : ArgumentTag {
  static constexpr auto type = ArgumentType::positional;
  using value_type = std::string;

  constexpr PositionalArgument(Requirement requirement = optional) : requirement_(requirement) {}

  [[nodiscard]] constexpr auto value() const noexcept -> const std::string& { return value_; }
  [[nodiscard]] constexpr auto provided() const noexcept -> bool { return provided_; }
  [[nodiscard]] constexpr auto isRequired() const noexcept -> bool {
    return requirement_ == Requirement::required;
  }

  template <class>
  friend class Parser;

 protected:
  auto parse(std::string_view sv) -> std::expected<void, ParseError> {
    value_ = std::string(sv);
    return {};
  }

  constexpr auto markProvided() noexcept -> void { provided_ = true; }

 private:
  Requirement requirement_ = optional;
  std::string value_;
  bool provided_ = false;
};

// ---- Aliases ----

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using StringArg = Arg<std::string, LongOpt, ShortOpt>;

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using StringListArg = Arg<std::vector<std::string>, LongOpt, ShortOpt>;

using StringPositional = PositionalArgument<std::string>;

// Short-form aliases
template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using StrArg = StringArg<LongOpt, ShortOpt>;

template <StringLiteral LongOpt, char ShortOpt = '\0'>
  requires(detail::IsValidLongOpt<LongOpt>() && detail::IsValidShortOpt(ShortOpt))
using StrListArg = StringListArg<LongOpt, ShortOpt>;

using StrPositional = StringPositional;
using StrPositionalArg = StringPositional;
using StrPosArg = StringPositional;

}  // namespace argon
// ---- end: include/argon/string_argument.hh ----
